name: Go

on:
  push:
    branches:
      - 'feature/**'

env:
  AWS_S3_UPLOAD_SESSION: gh-action-session-drcat
  AWS_S3_UPLOAD_REGION: us-east-1
  AWS_S3_UPLOAD_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ghactions-drcat-s3-upload

jobs:
  build-linux-amd64:
    strategy:
      matrix:
        go-version: ["1.17", "1.18", "1.19"]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_S3_UPLOAD_REGION }}
        role-to-assume: ${{ env.AWS_S3_UPLOAD_ROLE_ARN }}
        role-session-name: ${{ env.AWS_S3_UPLOAD_SESSION }}

    - name: Build and install debian
      run: |
        echo '---------------------------'
        echo "building $(./release.py -v)"
        echo '---------------------------'
        make clean 
        make package-release-deb
        yes | sudo apt-get install ./build/*.deb 
        drcat -version

    - name: Ensure uninstallable
      run: sudo apt-get -y remove ${{ env.PROG_NAME }}

    - name: Upload
      run: |
        ls build/
        ls dist/
        aws s3 cp ./build/* "s3://github-artifacts-zeebrow/drcat/latest-dev/debian/amd64/"
#        aws s3 cp ./build/*.deb "s3://github-artifacts-zeebrow/drcat/latest-dev/debian/amd64/"
#        aws s3 cp ./build/drcat-$(./release.py -v) "s3://github-artifacts-zeebrow/drcat/latest-dev/linux/amd64/"
#        aws s3 cp ./build/MD5SUMS "s3://github-artifacts-zeebrow/drcat/latest-dev/linux/amd64/"
