name: Go

on:
  push:
    branches: [ master ]

env:
  PROG_NAME: drcat

jobs:

  build-linux-amd64:
#    permissions:
#      id-token: write
#      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test
      run: go test -v && go build -o "$PROG_NAME" .

    - name: Install debian
      run: make clean && make package-deb && sudo apt install ./build/*.deb && "$PROG_NAME" -version

#    - name: Upload
#      run: |
#        aws s3 cp ./build/define.deb "s3://github-artifacts-zeebrow/define/latest-devel/$GOOS/$GOARCH/"
#        aws s3 cp "./build/$GOOS/$GOARCH/define-$GOOS-$GOARCH" "s3://github-artifacts-zeebrow/define/latest-devel/$GOOS/$GOARCH/"


  build-windows:
    runs-on: windows-latest
#    permissions:
#      id-token: write
#      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test Windows
      run: go build -o "$PROG_NAME".exe . && go test -v

    - name: Upload binaries
      run: |
        aws s3 cp "./build/$PROG_NAME.exe" "s3://github-artifacts-zeebrow/$PROG_NAME/latest-devel/$GOOS/$GOARCH/"
