name: Go

on:
  push:
    branches: [ master ]


jobs:

  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test
      run: go build -o fmt-md-text . && go test -v

    - name: Install debian
      run: make clean && make package-deb && sudo apt install ./build/*.deb && fmt-md-text -version

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test Windows
      run: go build -o fmt-md-text.exe . && go test -v
