# #############
# distribute release binaries
# We're only distributing what is built with the latest version of go
# This will be run on every commit to a branch with an open pull request to a
# release branch, and uploaded to s3 drcat/releases/
name: release

on:
  pull_request:
    branches:
      - 'release/*'

env:
  AWS_S3_UPLOAD_SESSION: gh-action-session-drcat
  AWS_S3_UPLOAD_REGION: us-east-1
  AWS_S3_UPLOAD_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ghactions-drcat-s3-upload

jobs:
  release-linux-amd64:
    strategy:
      matrix:
        # should only be latest
        go-version: ["1.19"]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ env.AWS_S3_UPLOAD_REGION }}
        role-to-assume: ${{ env.AWS_S3_UPLOAD_ROLE_ARN }}
        role-session-name: ${{ env.AWS_S3_UPLOAD_SESSION }}

    - name: Build .deb binary package
      run: |
        echo '---------------------------'
        echo "building $(./release.py -v)"
        echo '---------------------------'
        make VERSION=$(./release.py -v) package-release-deb

    - name: Upload
      run: |
        aws s3 cp ./build/drcat-$(./release.py -v).deb "s3://github-artifacts-zeebrow/drcat/releases/debian/$(./release.py -v)"
        aws s3 cp ./build/drcat-$(./release.py -v).deb.md5 "s3://github-artifacts-zeebrow/drcat/releases/debian/$(./release.py -v)"
        aws s3 cp ./build/drcat-$(./release.py -v) "s3://github-artifacts-zeebrow/drcat/releases/binary-linux-amd64/$(./release.py -v)"
        aws s3 cp ./build/drcat-$(./release.py -v).md5 "s3://github-artifacts-zeebrow/drcat/releases/binary-linux-amd64/$(./release.py -v)"

