name: release

on:
  push:
    branches:
      - 'release/**'
env:
  PROG_NAME: drcat
  AWS_S3_UPLOAD_SESSION: gh-action-session-drcat
  AWS_S3_UPLOAD_REGION: us-east-1
  AWS_S3_UPLOAD_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ghactions-drcat-s3-upload

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_S3_UPLOAD_REGION }}
        role-to-assume: ${{ env.AWS_S3_UPLOAD_ROLE_ARN }}
        role-session-name: ${{ env.AWS_S3_UPLOAD_SESSION }}
    - name: Check install debian
      run: |
        make clean 
        make package-deb 
        sudo apt -y install ./build/*.deb 
        drcat -version
        sudo apt remove -y drcat

    - name: Build and upload .deb release for version
      run : |
        export RELEASE_VERSION=$(./release.py -v)
        echo "$RELEASE_VERSION"
        make VERSION="$RELEASE_VERSION" release-deb
        aws s3 cp ./build/*.deb "s3://github-artifacts-zeebrow/drcat/releases/debian/v$RELEASE_VERSION/amd64/"
        aws s3 cp ./build/*.deb.md5 "s3://github-artifacts-zeebrow/drcat/releases/debian/v$RELEASE_VERSION/amd64/"
        aws s3 cp "./build/${{ env.PROG_NAME }}-$RELEASE_VERSION" "s3://github-artifacts-zeebrow/drcat/releases/binaries/v$RELEASE_VERSION/linux/amd64/"
        aws s3 cp "./build/${{ env.PROG_NAME }}-$RELEASE_VERSION.md5" "s3://github-artifacts-zeebrow/drcat/releases/binaries/v$RELEASE_VERSION/linux/amd64/"

    - name: Test release artifacts are downloadable
      run: |
        export RELEASE_VERSION=$(./release.py -v)
        make VERSION="$RELEASE_VERSION" test-release-deb
